### ISSUE TITLE
dvutils package not available for R version 3.5.2

### ISSUE THREAD

**Issue by soluna1** [pr2database/pr2database#13]
Hi, 

I'm trying to use pr2 database and it fails when plotting with dvutils. I've tried to install dvutils package but I've got the following answer:

Warning in install.packages :
  package ‘dvutils’ is not available (for R version 3.5.2)

Is there a solution for this issue?

thanks a lot.

**Comment by vaulot** [comment]
Can you tell me which line of code gives you this error and where you get the code for plotting ?  `dvutils` is a personal library that is not available, so I am wondering where you got the code... If you send the line, I will try to find the equivalent without using `dvutils`.

**Comment by soluna1** [comment]
Yes, sure, I'm following the code in this website:
https://vaulot.github.io/pr2/PR2_analysis.html#all-taxa

And this is the code that retrieves that problem:
dvutils::pr2_treemap(pr2, 3)
# to plot taxonomic composition at division level

I've downloaded the whole coding from
https://github.com/pr2database/pr2database/wiki/The-R-pr2database-package
Thanks for your prompt answer.

regards,

**Comment by soluna1** [comment]
Great!! thanks a lot!

**Comment by vaulot** [comment]
Hi
I updated the web page and now you should have all the code to reproduce the examples.  Let me know if you have other troubles.  Cheers.

**Comment by soluna1** [comment]
Hi,
Great thanks, it works perfectly now. 👍
