### ISSUE TITLE
Taxonomy file

### ISSUE THREAD

**Issue by yueliang1103** [pr2database/pr2database#16]
Dear Daniel,

I am trying to do taxonomy classification using KrakenUniq with the PR2 database.
In order to build a custom KrakenUniq database, a taxonomy database, specifically nodes.dmp and names.dmp, is required.
Could you please tell me where to download the PR2 taxonomy files? 
Thank you in advance.

Cheers,
Yue

**Comment by yueliang1103** [comment]
The following are the requirements for building a custom database for KrakenUniq.

Sequence files (FASTA format)
Mapping files (tab separated format, sequence header<tab>taxID
NCBI taxonomy files (though a custom taoxnomies may be used, too)

The taxonomy files are what I am looking for. They are nodes.dmp and names.dmp according to the format of NCBI taxonomy dumps.

We can easily generate a names.dmp using the files provided. It's more difficult but not completely impossible to generate a nodes.dmp for the PR2 database. However, I think it's always better to use the official version so that there won't be any bias introduced by different users.

**Comment by vaulot** [comment]
Dear Yue

Thanks for posting the question on GitHub...

PR2 is not structured the way Genbank taxonomy database is structured.  It has a taxonomy table (pr2_taxonomy.tsv in [pr2_taxons.zip](https://github.com/pr2database/pr2database/files/3168566/pr2_taxons.zip)) from which a taxon table can be generated on the fly (pr2_taxons.tsv in [pr2_taxons.zip](https://github.com/pr2database/pr2database/files/3168566/pr2_taxons.zip)).

Below is the r code to generate the pr2_taxons file from the pr2_taxonomy table. 

Let me know if this works for you. Cheers. Daniel

```
library(dplyr)
library(stringr)
library(readr)
library(tibble)

  pr2.env <- new.env()
  pr2.env$taxo_levels = c("kingdom", "supergroup", "division", "class", "order", "family", "genus", "species")
  pr2.env$taxo_levels_number =length(pr2.env$taxo_levels)

pr2_buid_taxons <- function(pr2_taxonomy, add_old_fields=FALSE) {

  # Initialize variables

    taxo_levels_number <- length(pr2.env$taxo_levels)
    taxo_list <- list()
    taxo_list_2_parents <- list()

  # Extract all taxo levels

  # Level 1 - Kingdom
    i <- 1
    taxo <- pr2_taxonomy %>%
            group_by_ (pr2.env$taxo_levels[1]) %>%
            summarise(number_of_taxa=n())
    taxo<-taxo %>% transmute(name=kingdom, taxa_number=number_of_taxa)
    taxo$level<-i
    taxo$id<-1:nrow(taxo)
    taxo$parent_id<-0
    taxo_list[[1]] <- taxo


  # Level 2 to 8

    for (i in c(2:taxo_levels_number)) {
      taxo_list[[i]] <-pr2_extract_one_taxo_level(pr2_taxonomy,
                                              pr2.env$taxo_levels[[i-1]],
                                              pr2.env$taxo_levels[[i]],
                                              i,
                                              taxo_list[[i-1]])
     }

  # Reduce the 8 lists to a single dataframe
    pr2_taxons <- taxo_list %>% reduce (bind_rows)

  # Get a serial number for the taxons
    pr2_taxons <- pr2_taxons %>% rowid_to_column(var="taxon_id")

  # Now replace the parent_id by the new id
    pr2_taxons_1 <- pr2_taxons %>% mutate(parent_level=level-1)

    pr2_taxons_2 <- pr2_taxons %>% select(parent_id_new=taxon_id, level, id)

    pr2_taxons_3 <- left_join(pr2_taxons_1, pr2_taxons_2, by = c("parent_level" = "level", "parent_id"="id"))

  # Change the names
    pr2_taxons_3 <- pr2_taxons_3 %>% select(taxon_id, taxon_name = name, taxon_level = level, parent_id = parent_id_new)

  # Left join to recover the old information from the pr2_taxonomy table

    if(add_old_fields==TRUE) {
    pr2_taxo_1 <- pr2_taxo %>% select(old_species_id = taxo_id,
                                      taxon_name=species,
                                      taxon_edited_version = taxo_edited_version,
                                      taxon_edited_by = taxo_edited_by,
                                      taxon_removed_version = taxo_removed_version,
                                      taxon_remark = taxo_remark,
                                      taxon_reference = reference)
    pr2_taxons_3 <- pr2_taxons_3 %>% left_join(pr2_taxo_1)
    }


    return(pr2_taxons_3)

}

```

**Comment by yueliang1103** [comment]
Dear Daniel,

Thank you very much for providing the files and codes.
I just checked the file and found something confusing.
Are the taxo_id in the pr2_taxonomy.tsv and the taxon_id in the
pr2_taxons.tsv the same ID?
If they are, from my understanding, the taxo_id 1 in pr2_taxonomy.tsv
represents Alveolata_XXXXX_sp. while the taxon_id 1 in pr2_taxons.tsv
represents Bacteria. Please correct me if I am wrong.

Cheers,
Yue

**Comment by yueliang1103** [comment]
After I read and ran the R code, I got the idea. Please ignore my previous response. 
I will then format the files according to the format of NCBI taxonomy dumps and use them in KrakenUniq. I will let everyone know if the analysis goes well.

**Comment by vaulot** [comment]
Dear Yue,
You are right the taxo_id and taxon_id are different.  The taxon_id is generated on the fly.  Let us know how it works and how it compares to other classifiers such as the Wang classifier implemented in dada2.  If this is of interest, I could put the necessary files to use KrakenUniq for read assignation in a future release of pr2.
Also, as note the version I send you corresponds pr2 4.12.0 which is not yet released and that will include plastid and cyanobacteria 16S sequences.  So better for you to regenerate the pr2_taxons.tsv from the current 4.11.0 version of the pr2 database.

**Comment by yueliang1103** [comment]
Dear Daniel,

Thank you for letting me know the version difference. I will build the
taxonomy files using the current version. There is a question. In the R
code you posted, the function pr2_extract_one_taxo_level is not defined. I
guess it based on the codes to generate the first taxo_list.

  taxo <- pr2_taxonomy %>%
  group_by_ (pr2.env$taxo_levels[i]) %>%
    summarise(number_of_taxa=n())
  taxo<-taxo %>% transmute(name=pr2.env$taxo_levels[i],
taxa_number=number_of_taxa)
  taxo$level<-i
  taxo$id<-1:nrow(taxo)
  taxo$parent_id<- ? # I can add it later though
  taxo_list[[i]] <- taxo

Could you please correct my codes?

Yue

**Comment by yueliang1103** [comment]
I am new to taxonomy classification so I didn't know much about the software available. Thank you for letting me know the Wang classifier in data2. I will also try it later.

**Comment by vaulot** [comment]
Oops sorry,

Here is the code for pr2_extract_one_taxo_level  (I have a personnal R library that codes a lot of these functions)

```
# pr2_extract_one_taxo_level -------------------------------------------------------------------------
#' Extract one level of taxonomy
#'
#' This function returns a data frame that contains:
#'
#' * name = name of the taxon
#' * taxa_number = number of taxa downstream of this taxon
#' * level = number of the level (e.g. genus = level number 7)
#' * parend_id = id of the first parent taxon  (sometimes one taxon has more than one taxon)
#' * id = id of the taxon (just the row name since they are ordered alphabetically )
#' @note
#' Here is an example at the genus level
#'   name	            taxa_number	    level	    parent_id	    id
#' Ascampbelliella	    1	              7	        51	          1
#' Choreotrichida_XX	  1	              7	        1	            2
#' Cyttarocylididae_X	1	              7	        52	          3
#' Cyttarocylis	      4	              7	        52	          4
#' Petalotricha	      1	              7	        52	          5
#' Codonaria	          2	              7	        53	          6
#' Codonella	          2	              7	        53	          7
#' @param pr2_taxo dataframe - taxonomy with 8 coumns kigdom -> species (but can be more)
#' @param level_above_name character - name of the taxo level above (e.g. "order")
#' @param level_name character - name the level considered (e.g. "family")
#' @param taxo_above dataframe -  the same structure than the output of the function but for the level above (e.g. the order if we are the family level)
#' @examples
#' genus_df <- pr2_extract_one_taxo_level(pr2_taxo, "family", "genus", 7, family_df)
#' @export
#' @md
  pr2_extract_one_taxo_level <- function(pr2_taxo, level_above_name, level_name, level_number, taxo_above) {
    taxo <-  pr2_taxo %>%
                group_by_ (level_above_name, level_name) %>%
                summarise(n=n()) %>%
                transmute_(name=level_name, number_of_taxa="n")
    taxo$level<-level_number
    taxo <-merge(taxo, taxo_above, all.x, by.x=level_above_name, by.y="name")
    taxo <- taxo %>%
      transmute_("name", taxa_number="number_of_taxa", level="level.x", parent_id = "id") %>%
      arrange(name) %>%
      rowid_to_column( var = "id")

    return(taxo)
  }
```

**Comment by vaulot** [comment]
Concerning https://github.com/pr2database/pr2database/issues/16#issuecomment-491586618

I think you should use the whole gene and not only the V9 region because you have very high chances to hit other parts of the gene...  The mothur assigner is the same as the Wang assigner implemented in dada2, so you can use either.  For sure which such short reads this is super challenging because probably you will hit most of the time very conserved regions... Good luck.

**Comment by yueliang1103** [comment]
Dear Daniel,

Thank you very much for the codes. I will let you know how the PR2 database works with KrakenUniq.

Yue

**Comment by yueliang1103** [comment]
The taxonomy classification using KrakenUniq with the customized taxonomy files of the PR2 database works very well. KrakenUniq recognizes the taxonomy hierarchy and gives the read counts for each different taxonomy ranks. There are quite a few Ns in the database which gave warnings as "Bad characters in sequences" during database building of KrakenUniq. I have no idea how the Ns will affect the classification. I am contacting the KrakenUniq developer to confirm this issue. KrakenUniq is designed for using whole genome sequences as the database. I am also contacting them to see if the short 18S sequences will potentially introduce more false positives.

**Comment by vaulot** [comment]
Thanks Yue, 
Would be really interesting to see how it performs in comparison to dada2 assignTaxonomy function in terms of precision and speed...

**Comment by yueliang1103** [comment]
Dear Dianel,

We finally got the results of Mothur. Unfortunately, the results of Mothur is very different from the results of KrakenUniq. The Mothur results show the dominance of diatoms (30% more than the results of KrakenUniq) while very few chlorophyta get annotated. We used 18s full length rRNA sequences to build the database. Our reads are short as around 80 nt. I don't know if the short read length created any problem. The changes of taxon distribution across treatments are similar using either method. Since we only want to discuss the changes across different treatments, we are fine with these technique biases. 

Best,
Yue

**Comment by vaulot** [comment]
Dear Yue

Thanks a lot for the feedback.  Well I think very short reads are not ideal because as you know the 18S has very conserved and very variable regions.  So if your short sequence hits a conserved region then taxonomy would be very uncertain. In contrast, if you hit a highly variable region then it would be much better assigned.  Even if you are only considering relative changes, I would still be very very careful... Best.  Daniel
