### ISSUE TITLE
Missing genus

### ISSUE THREAD

**Issue by soluna1** [pr2database/pr2database#18]
Hi, 

I've just noticed that the diatom genus Bacteriastrum is not represented in the database. Some examples that could be included are:
Accession MG972355.1 Bacteriastrum hyalinum
Accession GQ330314 Bacteriastrum hyalinum
Accession MG972357.1 Bacteriastrum jadranum

I don't know about other areas, but is quiet common in the south mediterranean basin. 
Many thanks,

**Comment by vaulot** [comment]
Dear Soluna
They will be added in the next release (4.12.0, release in early August) as well as the update of the Chaetoceros genus reported in the C.C. Gaonkar et al. paper in PLOS One.

Thanks for your contribution to PR2. Daniel

**Comment by soluna1** [comment]
Thanks for your reply, great news also to hear about the new release.

**Comment by vaulot** [comment]
The new version of PR2 has now the updated Chaetoceros and Bacteriastrum as well...

**Comment by soluna1** [comment]
Yeeessss,  I've just downloaded it! and there are Bacteriastrum and new chaetoceros in it! thanks a lot.
