### ISSUE TITLE
replicate entries in pr2 4.12.0

### ISSUE THREAD

**Issue by shu251** [pr2database/pr2database#20]
I'm getting replicate entries in v 4.12.0. Taxa entry is identical, but sequence entry is different. I'm trying to use the mothur fasta and tax files in a pipeline to train PR2 for use in QIIME2 ASV determination and tax assignment - these duplicate entries throw an error.

Replicate entries: KC486130.1.1651_U, AB275104.1.1590_U, EU087243.1.813_U, EU087247.1.847_U, FJ459738.1.1634_U

I know this was an issue from the last release and it was updated quickly. Is there an additional script you can include with each release that performs this de-duplication?
https://github.com/shu251/db-build-microeuks

**Comment by vaulot** [comment]
Hi Sarah

Thanks for pointing out this issue (this was due to repeated sequences in the pr2_sequence table).  I have added one more check to ensure that this will not occur in future releases.

I have fixed the files from the 4.12.0 release as well as the pr2database R package.  Cheers.  Daniel
