### ISSUE TITLE
version 4.12 : presence of unrecognize char in sequence ID

### ISSUE THREAD

**Issue by mariabernard** [pr2database/pr2database#24]
Hello,

I downloaded the fasta file (pr2_version_4.12.0_18S_taxo_long.fasta.gz) to format it for the FROGS pipeline (basically formatting for BLAST and RDP classifier).

I encountered some troubles with makeblastdb because of unrecognized char in sequences identifier: 
- `Ã©` that I change with a simple `e`, my guess is that it was a french `é`
- `Ã»` that I change with a simple `u`, my guess is that it was a french `û`

problematic sequences ID are:
>FJ660684.1.1753_U|18S_rRNA|nucleus|strain_14-fÃ©vr.
>FJ609422.1.1913_U|18S_rRNA|nucleus|specimen_10-aoÃ»t
>FJ660668.1.1752_U|18S_rRNA|nucleus|strain_02-fÃ©vr.
>FJ660680.1.1752_U|18S_rRNA|nucleus|strain_13-fÃ©vr.
>FJ660676.1.1751_U|18S_rRNA|nucleus|strain_12-fÃ©vr.
>EU667999.1.1679_U|18S_rRNA|nucleus|strain_12-fÃ©vr.
>EU667995.1.1682_U|18S_rRNA|nucleus|strain_07-fÃ©vr.
>FJ660672.1.1752_U|18S_rRNA|nucleus|strain_11-fÃ©vr.
>EU667999.1.1679_UC|18S_rRNA|nucleus|strain_12-fÃ©vr.
>EU667995.1.1682_UC|18S_rRNA|nucleus|strain_07-fÃ©vr.

just to let you known

Kindly

Maria

**Comment by vaulot** [comment]
Hi Maria

Thanks a lot for noticing this... It was a bit of tricky error. When reading the Genbank records some fields (like strain) were recognized like dates and formatted as French dates.  I fixed it in the database and the next release should be fine.

Best.  Daniel
