### ISSUE TITLE
entries that may be in the wrong orientation (reverse, complement or both)

### ISSUE THREAD

**Issue by frederic-mahe** [pr2database/pr2database#28]
While working with cutadapt (v3.4) to extract the SSU V4 region, I've noticed that some entries are not in the expected orientation (compared to the reference _Saccharomyces_ _cerevisiae_). I wrote a script to search for all possible orientations:

```sh
## primers from Stoeck et al. 2010
ORIGINAL_PRIMER_F="CCAGCASCYGCGGTAATTCC"
ORIGINAL_PRIMER_R="ACTTTCGTTCTTGATYRA"


complement() {
    # complement a DNA/RNA IUPAC string
    [[ -z "${1}" ]] && { echo "error: empty string" ; exit 1 ; }
    local -r nucleotides="acgturykmbdhvswACGTURYKMBDHVSW"
    local -r complements="tgcaayrmkvhdbswTGCAAYRMKVHDBSW"
    tr "${nucleotides}" "${complements}" <<< "${1}"
}


trim_primers() {
    # trim and keep only entries with both primers
    OPTIONS="--minimum-length ${MIN_LENGTH} --discard-untrimmed --error-rate ${ERROR_RATE} --quiet"
    CUTADAPT="$(which cutadapt) ${OPTIONS}"
    MIN_LENGTH="32"
    ERROR_RATE="0.2"
    MIN_F=$(( ${#PRIMER_F} * 2 / 3 ))
    MIN_R=$(( ${#PRIMER_R} * 2 / 3 ))

    zcat "${SOURCE}.gz" | \
        dos2unix | \
        ${CUTADAPT} \
            --front "${PRIMER_F}" \
            --overlap "${MIN_F}" - | \
        ${CUTADAPT} \
            --adapter "${PRIMER_R}" \
            --overlap "${MIN_R}" - > "${OUTPUT}"
}

## download PR2 (UTAX version)
URL="https://github.com/pr2database/pr2database/releases/download"
VERSION="4.13.0"
SOURCE="pr2_version_${VERSION}_18S_UTAX.fasta"
[[ -e "${SOURCE}.gz" ]] || wget "${URL}/v${VERSION}/${SOURCE}.gz"


## search rev-comp entries
OUTPUT="revcomp.fas"
PRIMER_F="${ORIGINAL_PRIMER_R}"
PRIMER_R="$(complement "${ORIGINAL_PRIMER_F}" | rev)"
trim_primers


## search reverse entries
OUTPUT="reverse.fas"
PRIMER_F="$(complement "${ORIGINAL_PRIMER_R}")"
PRIMER_R="$(rev <<< "${ORIGINAL_PRIMER_F}")"
trim_primers


## search complement entries
OUTPUT="complement.fas"
PRIMER_F="$(complement "${ORIGINAL_PRIMER_F}")"
PRIMER_R="$(rev <<< "${ORIGINAL_PRIMER_R}")"
trim_primers
```
The script allows 20% of errors in primer matching but forces a match greater or equal to 2/3rd of the primer length. That parameter should limit false positives.

The results are:
- 115 possible case of 'reverse-complement' sequences (a frequent mistake),
- 30 possible cases of 'complement' sequences (rare, but I've seen 'complement' 18S entries on GenBank),
- 1 possible case of 'reverse' sequence

I join the corresponding fasta files: [misoriented_entries.zip](https://github.com/pr2database/pr2database/files/6310053/misoriented_entries.zip)

**Comment by vaulot** [comment]
Merci bcp Fred

Je vais mettre à jour les séquences en question.  Daniel

**Comment by vaulot** [comment]
Salut Fred

I checked the sequences and 6 were removed because they seem to have a probem (do not BLAST with similar taxa):
JL712519|AF542044|AY223840|AY237160|KF747308|HQ660595

For the other sequences, the rev comp or comp seemed to solve the issue.  This will updated in 4.14.0. 

Thanks for the help

**Comment by frederic-mahe** [comment]
I though about an alternative approach that does not require primers, but is limited to
finding reverse-complement entries:
```sh
  PR2="pr2_version_4.13.0_18S_UTAX.fasta.gz"

  # with vsearch 2.17 or more recent
  vsearch \
      --orient "${PR2}" \
      --db "${PR2}" \
      --quiet \
      --tabbedout - | \
      awk '$2 == "-"'
```
```
  Forward oriented sequences: 178470 (99.82%)
  Reverse oriented sequences: 303 (0.17%)
  All oriented sequences:     178773 (99.99%)
  Not oriented sequences:     21 (0.01%)
  Total number of sequences:  178794
```
Here are the entries identified as likely reverse-complement when compared to the others: [rev_comp.txt](https://github.com/pr2database/pr2database/files/6338097/rev_comp.txt). The number of false-positives could be high though, so maybe there is no need to act on these sequences right now?

**Comment by vaulot** [comment]
Bonjour Fred

I checked all your sequences using BLAST.  Some where in the list before but all the new ones were in the wrong orientation.  I corrected in the PR2 database.  So the script works really well.... and it will be useful to test all the other sequences that are not annotated yet.

Bon week-end.

**Comment by frederic-mahe** [comment]
Hi Daniel, nice work on version 4.14!  vsearch identifies only two sequences as rev-comp:
```
Forward oriented sequences: 197582 (99.99%)
Reverse oriented sequences: 2 (0.00%)
All oriented sequences:     197584 (99.99%)
Not oriented sequences:     18 (0.01%)
Total number of sequences:  197602

ABIR02004321.1.998_U;tax=k:Eukaryota,d:Opisthokonta,p:Metazoa,c:Nematoda,o:Enoplea,f:Enoplea_X,g:Trichinella,s:Trichinella_spiralis	-	90	649
AM887495.1.875_U;tax=k:Eukaryota,d:Opisthokonta,p:Fungi,c:Ascomycota,o:Pezizomycotina,f:Dothideomycetes,g:Pyrenophora,s:Pyrenophora_tritici-repentis	-	120	500
```
I can open a dedicated issue if need be.

**Comment by vaulot** [comment]
Merci Fred, super non pas de soucis je les mets à jour dans la base.
