### ISSUE TITLE
How to use PR2 with assignTaxonomy from DADA2?

### ISSUE THREAD

**Issue by johnne** [pr2database/pr2database#31]
Hi!
I'm trying to use the PR2 database with the `assignTaxonomy` function from DADA2 to assign taxonomy to rRNA sequences in a fastq file. I found a note about using the taxLevels `c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species")` but I wonder how this compares to taxonomic assignments for 16S sequences (which I suspect may also be included in my sequence file) where the taxLevels only go down to genus and then a separate training fasta is used to assign species? 

If I want to make taxonomic assignments consistent between 18S and 16S, should I skip species from the PR2 training fasta header and add it separately with the `addSpecies` function?

Thanks in advance for any help and for a good resource!

**Comment by vaulot** [comment]
Hi

You can use all the taxonomic levels down to species when you use assignTaxonomy. This is true for both Euks and Prok (PR2 has a small number of representative Prok sequences).  I personally never use assignSpecies which is only useful when you want to make sure that the sequence of your ASV is 100% identical to a reference species sequence.

**Comment by johnne** [comment]
Thank you for the reply!
