### ISSUE TITLE
pr2_version_4.14.0_SSU.decipher.trained.rds

### ISSUE THREAD

**Issue by romaro-gomes** [pr2database/pr2database#33]
Hello professor!

I tried using this trained dataset for my analyses, but its seems corrupt.

Thank you! :D

**Comment by vaulot** [comment]
Hi
Very difficult to help you with so little information.  Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) ?

**Comment by romaro-gomes** [comment]
Hello professor!

The probleam was solved

It was that
Example:
> load("pr2_version_4.14.0_SSU.decipher.trained.rds")

return:
Error in load("pr2_version_4.14.0_SSU.decipher.trained.rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file ‘pr2_version_4.14.0_SSU.decipher.trained.rds’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 

I used readRDS function, and it worked now

**Comment by romaro-gomes** [comment]
Thanks for your attention.

**Comment by vaulot** [comment]
Hi 
Thanks for the feedback.  You can read more on the use of DECIPHEr [here](https://pr2database.github.io/pr2database/articles/pr2_04_decipher.html).
