### ISSUE TITLE
Training a custom database for classification

### ISSUE THREAD

**Issue by FarzanehRah** [pr2database/pr2database#35]
Hello,
I used your script #26 to train a database for the `IdTaxa ` function in the `DECIPHER `package. However, after classification, the majority of sequences are classified as a specific species that does not match the results from NCBI blast.

My database is built with around 1.5 million COI sequences from NCBI. I would appreciate your advice on:

1. Determining the best values for `maxGroupSize `and `maxIterations` for database training.
2. Understanding whether the length of the sequence in the database has any impact on the classification result. ( some of the sequences collected from NCBI in my database are over 1 million in length)

Thank you in advance for your assistance.

**Comment by vaulot** [comment]
Hi

I think this is a question for the developer of DECIPHER and not for PR2
http://www2.decipher.codes/Contact.html

Moreover, I think that if you to train DECIPHER for COI, you should only use the sequence of COI and not longer sequence that should be either trimmed to the COI region or remove all together.

Best.  Daniel
