### ISSUE TITLE
Cryothecomonas aestivalis

### ISSUE THREAD

**Issue by dcat4** [pr2database/pr2database#36]
Hi there, I've noticed PR2 incorporates only 1 of 2 strains of Cryothecomonas aestivalis reference sequences from Kuhn et al. 2000 (https://www.sciencedirect.com/science/article/pii/S1434461004700322).

Strain 2 from that study (genbank accession AF290541.1) does not appear to be included in PR2 version 5.0.0 nor in 4.14.0. 

I can't find any follow-up studies to suggest this reference should be excluded so just pointing out in case this exclusion is unintentional. 

Thanks for all your hard work developing and maintaining this excellent resource.

**Comment by vaulot** [comment]
Hi Dylan

The sequence AF290541.1 contains 2 consecutive N and therefore does not fulfill the criteria to be included in PR2.  Probably the next version of PR2 will relax this rule to only remove sequences with 3 or more consecutive N.

The rules for inclusion in R are here: 
https://pr2-database.org/documentation/pr2-structure/

Thanks a lot for your feedback. Daniel
