### ISSUE TITLE
non-ascii character in PR2 5.0

### ISSUE THREAD

**Issue by frederic-mahe** [pr2database/pr2database#37]
Hello,

in the entry `MF423350` (_Heterocapsa steinii_), the 'space' in the species name is not an ascii space. It is encoded by a 16-bit character `$C2A0`, where it should be a simple 8-bit value `$20`. That creates an error when processing this release with `cutadapt`:
```
>MF423350.1.1769_U;tax=k:Eukaryota,d:TSAR,p:Alveolata-Dinoflagellata,c:Dinophyceae,o:Peridiniales,f:Heterocapsaceae,g:Heterocapsa,s:Heterocapsa steinii
```

It seems to be the only non-ascii character in that release:
```sh
zgrep --color='auto' -P -n '[^\x00-\x7F]' pr2_version_5.0.0_SSU_UTAX.fasta.gz
```

**Comment by vaulot** [comment]
Thanks Fred

Super good catch... I will upload the updated files in a bit.

Cheers. Daniel

**Comment by vaulot** [comment]
Update done...

**Comment by frederic-mahe** [comment]
Thanks Daniel! I am happy to help, though I am sorry I did not catch that before the release.
