### ISSUE TITLE
Query fails on online DB

### ISSUE THREAD

**Issue by nvpatin** [pr2database/pr2database#41]
Hello, when I enter a 349-nt sequence into the query field online, I consistently get the following message: "An error has occurred. Check your logs or contact the app author for clarification."

I don't see anywhere to download or view the log files. The sequence is annotated on NCBI as belonging to the Order Dinophyceae. Any thoughts?

**Comment by vaulot** [comment]
Hi Nastassia

Thank you for the query.  The logs are for internal use but I can check them on the server.  

Can you send me the sequence you are trying to BLAST in the exact form that you are using for the query.

Thanks in advance.  Cheers.

**Comment by nvpatin** [comment]
Thanks for the quick response. The nucleotide sequence I am running is:

ATTAAGTACTTCCTTCATGAGTTTATCTCCTTCTAGCACTGCTTATATTATATTTGGATTATTAATGGCTGGAATATCCTCCTGTGTCACGTCTCTTAACTTTTGGGTTACAATATTAAATATGAGATGTTACAGTCTCACATTAAAAACTATGGTATTATTCTCTTGGAGTCTTTTGATTACTGGAGCTATGCTTTTATTAACATTGCCAGTATTAACAGGAGCTCTTCTTATGATATTGTCTGATCTTCATTGTAATACTCTTTTATTTGATCCAGTTTTTCTTGGAGACCCTGTACTCTATCAACATT

I enter exactly as above, with no header.

**Comment by vaulot** [comment]
Hi Nastassia

When I BLAST this sequence against GenBank, I do not find any hit.  This is the same what is happening with PR2 (since PR2 is just a subset of GenBank sequences).  Still there is bug and it should return that there is no significant hit....  I will fix for the next release.

![image](https://github.com/pr2database/pr2database/assets/24701681/f6440535-87be-4e58-886c-fc4afc5842ed)

**Comment by nvpatin** [comment]
That's true for megablast, but when I use blastn I get hits with ~83% identity. I guess I was hoping PR2 would have additional or more confident annotations but if it has the exact same sequences as GenBank then this makes sense. Thanks for clarifying!
<img width="1269" alt="Screenshot 2023-10-19 at 10 28 53 AM" src="https://github.com/pr2database/pr2database/assets/7750157/b98be95d-2630-403e-9cf3-c75dd39a4951">

**Comment by vaulot** [comment]
Hi Nastassia

Just to wrap up... PR2 is ONLY 18S rRNA sequences and your sequence comes from the cox1 mitochondrial gene which is not covered by PR2.

Best.
