### ISSUE TITLE
Arthropoda level seems to be incorrect

### ISSUE THREAD

**Issue by michellekyu** [pr2database/pr2database#43]
Dear developer,

I'm using PR2 and mothur to do taxonomic assignment on my 18S metabarcoding data. I found that Maxillopoda, Branchiopoda, and Insecta etc. were assigned to the Family level, but they should be in the Class level. The entire Metazoa seems to be shifted... Could you please have a look at the issue? Thanks and have a good one!

Best,
Michelle

**Comment by vaulot** [comment]
Hi Michelle

Thank you for your message.  Unfortunately, PR2 using a fixed number of levels (currently 9) does not offer much flexibility and we have chosen to compress some taxonomy paths, which is at odd with the recognized taxonomy.  Having Insecta at the class level would not allow squeezing the existing higher taxonomic path (Arthropoda	Hexapoda) between "subdivision" and "class".  PR2 is not really optimized for Metazoa unfortunately, and we will have an in-depth look in the future, but this will take some time.

Thank you again for your support of PR2. Daniel

**Comment by michellekyu** [comment]
Hi Daniel,

Thanks for your prompt reply!

Do you have any recommendations on reference database if I would like to focus on metazoan? Thanks!

Best,
Michelle

From: Daniel Vaulot ***@***.***>
Date: Monday, January 8, 2024 at 5:10 PM
To: pr2database/pr2database ***@***.***>
Cc: Michelle Cheng ***@***.***>, Author ***@***.***>
Subject: Re: [pr2database/pr2database] Arthropoda level seems to be incorrect (Issue #43)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Michelle

Thank you for your message. Unfortunately, PR2 using a fixed number of levels (currently 9) does not offer much flexibility and we have chosen to compress some taxonomy paths, which is at odd with the recognized taxonomy. Having Insecta at the class level would not allow squeezing the existing higher taxonomic path (Arthropoda Hexapoda) between "subdivision" and "class". PR2 is not really optimized for Metazoa unfortunately, and we will have an in-depth look in the future, but this will take some time.

Thank you again for your support of PR2. Daniel

**Comment by vaulot** [comment]
Unfortunately at present for 18S there is no good database for Metazoans...

**Comment by michellekyu** [comment]
I see… Many thanks and have a good day!

From: Daniel Vaulot ***@***.***>
Date: Monday, January 8, 2024 at 5:15 PM
To: pr2database/pr2database ***@***.***>
Cc: Michelle Cheng ***@***.***>, Author ***@***.***>
Subject: Re: [pr2database/pr2database] Arthropoda level seems to be incorrect (Issue #43)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Unfortunately at present for 18S there is no good database for Metazoans...
