### ISSUE TITLE
PR2 uses a different taxonomy ID code than NCBI taxonomy?

### ISSUE THREAD

**Issue by callAgene** [pr2database/pr2database#45]
For example, the taxo_id of the species *Halteria grandinella* recorded in the table *pr2_version_5.0.0_merged.csv* is 1512, whereas 1512 stands for cellular organisms in NCBI taxonomy is *Bacteria. Terrabacteria group; Bacillota; Clostridia; Lachnospirales; Lachnospiraceae; Lachnoclostridium*.

All the other ids also differ from the one in Taxonomy.

Is there an appropriate tool that will allow me to convert this to the NCBI taxonomy ID?

**Comment by vaulot** [comment]
Hello

Unfortunately, there is no correspondence between the taxo_id from PR2 and the NCBI taxonomy.  One fundamental reason is that PR2 taxonomy has a fixed number of levels from domain to species, while the number of ranks of NCBI is variable.  You can try to merge the two by a join made at the species level.

**Comment by callAgene** [comment]
Thank you very much for your advice.
