### ISSUE TITLE
Assigning taxonomy to ASVs by blastn

### ISSUE THREAD

**Issue by gennuowang** [pr2database/pr2database#46]
Hello PR2 team,

I made the pr2 custom database, like:
$ makeblastdb -in <input_fasta> -parse_seqids -blastdb_version 5 -title "custom_db_title" -dbtype nucl
now, I want to assign taxonomy to ASVs by blastn, the command as below:

#blastn
 blastn -task megablast -db /../db/pr2/species_taxid.fasta -query ../ASV_sequences.fasta -out 1_ASV.blastn -perc_identity 70 -outfmt '7 qseqid sseqid pident qcovs mismatch gapopen qstart qend sstart send evalue bitscore' -max_target_seqs 50 -num_threads $(($processes*$threads))

# Add tax info
awk 'BEGIN {OFS=FS="\t"} NR==FNR{map[$1]=$2;next} {for(i=1;i<=NF;i++)$i=($i in map)?map[$i]:$i}1' /../db/pr2/taxonomy.tsv 1_ASV.blastn > 2_ASV_lineage.blastn
I used like the **tax_id like 1006** in taxonomy.tsv to match **emu_db:1006**, it has 111 replicates. If two ASVs have the same first field (i.e. 1006 in this example), they will have the same classification information, which may result in two ASVs being incorrectly assigned to the same classification information.
Do you have any suggestions to add taxonomy to the ASV table?

Thank you very much!
Best, Wang

**Comment by vaulot** [comment]
Hi

I am really sorry but I do not understand what your question is.  Also I am not so familiar with awk syntax.  So please can you explain in simple term what you want to do and provide extract (a few lines) of the different files you want to do (please note that GitHub use markdown so please check the formatting of your message).
PS. pr2_version_5.0.0_emu_db.tar.gz files are for use with the [emu](https://gitlab.com/treangenlab/emu) pipeline.  If you want to do BLAST, I would recommend that you use the file [pr2_version_5.0.0_SSU_taxo_long.fasta.gz](https://github.com/pr2database/pr2database/releases/download/v5.0.0/pr2_version_5.0.0_SSU_taxo_long.fasta.gz).

Cheers.  Daniel
